name: Build landingpage

on:
  pull_request:
    branches: ["main"]
  release:
    types: ["published"]

env:
  BUILD_NAME: landingpage
  BUILD_TYPE: landingpage

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      channel: ${{ steps.version.outputs.channel }}
      publish: ${{ steps.version.outputs.publish }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master
        with:
          type: ${{ env.BUILD_TYPE }}

  build:
    name: Build ${{ matrix.machine }} landingpage
    needs: init
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        machine:
          # amd64 targets:
          - generic-x86-64
          - qemux86-64
          # arm64 targets:
          - khadas-vim3
          - odroid-c2
          - odroid-c4
          - odroid-m1
          - odroid-n2
          - qemuarm-64
          - raspberrypi3-64
          - raspberrypi4-64
          - raspberrypi5-64
          - yellow
          - green
        include:
          # aarch64 by default (keep first so the amd64 overrides below win)
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
          # amd64 machines
          - machine: generic-x86-64
            arch: amd64
            runs-on: ubuntu-24.04
          - machine: qemux86-64
            arch: amd64
            runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Build landingpage
        uses: home-assistant/builder/actions/build-image@4de35182ce1e329181bffcbcc84d33db5e2c7e10 # 2026.06.0
        with:
          arch: ${{ matrix.arch }}
          cache-image-tag: landingpage
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/home-assistant/${{ matrix.machine }}-homeassistant
          image-tags: |
            landingpage
            landingpage-${{ needs.init.outputs.version }}
          push: ${{ needs.init.outputs.publish == 'true' }}
          # version must be "landingpage" until this is resolved: https://github.com/home-assistant/supervisor/issues/6934
          version: landingpage
